# -*- coding: utf-8 -*-
"""8reinas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNvuXgyDJ6Qvx1KphMa5PomKzDBLU6QC
"""

def Reinas(solucion,etapa,n):
	if etapa>=n:                             
		return False
	exito = False                           
	
	while True:
            if (solucion[etapa] < n):                      
                solucion[etapa] = solucion[etapa] + 1       

            if (Valido(solucion,etapa)):                   

                if etapa != n-1:                            
                    exito = Reinas(solucion, etapa+1,n)
                    if exito==False:                        
                        solucion[etapa+1] = 0

                else:
                    print(solucion)                         
                    exito = True
            if (solucion[etapa]==n or exito==True):         
                break
	return exito


def Valido(solucion,etapa):
	for i in range(etapa):
		if(solucion[i] == solucion[etapa]) or (ValPos(solucion[i],solucion[etapa])==ValPos(i,etapa)):
			return False

	return True

def ValPos(x,y):
	if x>y:
		return x - y
	else:
		return y - x	

reinas = 8
solucion = []
for i in range(reinas):
	solucion.append(0)
etapa = 0
print(Reinas(solucion, etapa, reinas))

"""Analisis cualitativo:

Este algoritmo de las 8 reinas se basa en colocar en el tablero las 8 reinas de manera en que ninguna se pueda comer con la otra.

Como funciona?

Se tiene que ir verificando que las etapas sean menores que la cantidad de reinas porque por asi decirlo de ser mayor seria como que se saliera del tablero.

la funcion de las Reinas se encarga de ir verificando las columnas (etapas) con fila viendo que las reinas no se puedan comer entre ellas para verificar la mejor posicion para colocarse, pero esto se cumple gracias a la funcion Valido que es la escargada de hacer backtracking y ver las mejores posibilidades para colocarse asi que combinando estas 2 funcionan como La Reinas se posiciona con recorridos y Valido verifica si es una posicion optima, Al final se imprime un arreglo que representa las columnas y en que posicion se tiene que colocar la reina despues de esto retorna un True si esto fue posible.
"""